// Generated by LiveScript 1.5.0
(function(){
  var express, requireLs, ddos, app;
  express = require('express');
  requireLs = require('require-ls');
  ddos = require('./ddos.ls');
  app = express();
  app.use(ddos({
    'static': 1000,
    api: 1000,
    ban: 10 * 1000
  }));
  app.listen(8080);
}).call(this);
